apiVersion: v1
kind: Service
metadata:
  name: node-hello-app
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    app: node-hello-app
